test
Signed-off-by: Corey Hemminger <hemminger@hotmail.com>

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -9,8 +9,29 @@ jobs:
       - uses: actions/checkout@v3
       - name: Test script
         timeout-minutes: 1
-        shell: bash
-        run: ./ghaction_script.sh
+        run: |
+          #!/bin/bash
+          exit_script() {
+            echo "Received signal: $1"
+            echo "Going to kill a process"
+            trap - SIGHUP SIGINT SIGTERM # clear the trap
+            # Do stuff to clean up
+            exit
+          }
+          trap 'exit_script SIGHUP' SIGHUP
+          trap 'exit_script SIGTERM' SIGTERM
+          trap 'exit_script SIGINT' SIGINT
+          echo "running the job! PID: $$"
+          i=0
+          while true;
+          do
+            sleep 1;
+            i=$((i+1))
+            echo "$(hostname) $i";
+          done  
+          echo "Script finished Done"
+
+# run: ./ghaction_script.sh
 
 #---
 #on:
